Feature/header
bildvitta/nave pull request #1
Opened 2020-09-08 22:39 UTC by gqueiroz1

2020-09-09 14:29 UTC, DouglasCalora requested changes

2020-09-09 14:29 UTC, DouglasCalora commented on components/Header.vue
> +        <a class="duration-200 hover:text-nave-purple transition" href="#about">sobre</a>
faz um v-for loopando um obj

2020-09-09 14:29 UTC, DouglasCalora commented on tailwind.config.js
> +      'primary-hover': '#8A46EA',
precisa estar em string essas variaveis?

2020-09-09 14:32 UTC, DouglasCalora requested changes

2020-09-09 14:32 UTC, DouglasCalora commented on components/Header.vue
>        </nuxt-link>
vamos manter um padrao para os nomes dos componentes, o rafinha colocou `NaveFooter` ai aqui seria `NaveHeader` `Nave` seria o prefixo.

2020-09-09 16:40 UTC, gqueiroz1 commented on tailwind.config.js
> +      'primary-hover': '#8A46EA',
'primary-hover' precisa.. primaryHover nao funciona

2020-09-09 20:03 UTC, DouglasCalora requested changes

2020-09-09 20:03 UTC, DouglasCalora commented on components/Home.vue
> +  .container-home {
o nome deve começar com o nome do componente

2020-09-09 20:03 UTC, DouglasCalora commented on components/Home.vue
> +  .container-home {
indentação errada na classe

2020-09-09 20:03 UTC, DouglasCalora commented on components/NaveHeader.vue
> +.header {
nome do componente

2020-09-09 20:03 UTC, DouglasCalora commented on components/NaveHeader.vue
> +<style>
ja que esta pegando globalmente, pq n colca em um style global?

2020-09-09 23:47 UTC, caiotarifa requested changes

2020-09-09 23:47 UTC, caiotarifa commented on components/LinkButton.vue
> +    },
Não é melhor fazer ao contrário? A opção chamar `rounded` e ser `true` por default? Para desativar é só fazer `:rounded="false"`.

2020-09-09 23:47 UTC, caiotarifa commented on components/LinkButton.vue
> +  },
Isso me parecem classes e não cores. Recomendo um vetor indexado pelo nome da cor e o resultado as classes que devem ser aplicadas quando aquela cor for escolhida, por exemplo:

```js
const backgroundColors = {
  primary: 'bg-gradient-to-r from-primary hover:from-primary-hover hover:to-secondary-hover to-secondary'
}
```

e no Vue o usuário poderia passar apenas `primary` ou `secondary` para a prop.

``` js
export default {
  props: {
    backgroundColor: {
      default: 'primary',
      type: String
    }
  },

  computed: {
    backgroundColorClasses () {
      return backgroundColors[this.backgroundColor]
    }
  }
}
```

Obs: o mesmo vale para a cor do texto.

2020-09-09 23:47 UTC, caiotarifa commented on components/NaveHeader.vue
> +        }
Manter o `label` com a primeira letra maiúscula e estilizar com CSS (padrão semântico).__

2020-09-09 23:47 UTC, caiotarifa commented on components/NaveHeader.vue
> +    moveToTop () {
Recomendo trocar `move` por `scroll`, pois é o como esse efeito é chamado.

2020-09-09 23:47 UTC, caiotarifa commented on tailwind.config.js
> +      primary: '#7F2BED',
Avisei no PR do @Far3llProject e vou avisar aqui também, ao invés de `...theme(` use o `extend` do Tailwind.

2020-09-09 23:47 UTC, caiotarifa commented on tailwind.config.js
> +      'primary-hover': '#8A46EA',
Acha que daria para usar o padrão de color do Tailwind? Como `blue-100` ou `blur-400`? Não poderia ser `primary-500` ao invés de `primary-hover`?

2020-09-09 23:47 UTC, caiotarifa commented on tailwind.config.js
> +      'nave-purple': '#7C34EF'
White já existe, não? E `nave-purple` não pode ser apenas `purple`? Lembrar de fazer as sombras de `100` a `900`.

2020-09-10 13:12 UTC, gqueiroz1 commented on components/NaveHeader.vue
> +            v-for="link in links"
```<a v-for="(link, index) in links" :key="index"
             class="cursor-pointer duration-200 hover:text-nave-purple mr-10 transition"
             :class="activeSection(link.href)"
             :href="link.href"
          >
            {{ link.label }}
          </a>```

A class é muito grande, sempre passa de 120 cols, tem que quebrar de qualquer jeito

2020-09-10 13:16 UTC, gqueiroz1 commented on components/NaveHeader.vue
> +<style>
Codigo do rafa, corrigido.

2020-09-10 13:17 UTC, gqueiroz1 commented on components/NaveHeader.vue
> +      const hash = this.$route.hash
Esse método será removido e um novo implementado no lugar.
Fazer o active pelo scroll ao invés de deixar na rota.

2020-09-10 20:13 UTC, DouglasCalora approved these changes

2020-09-10 20:21 UTC, merged