Feature/about
bildvitta/nave pull request #5
Opened 2020-09-11 20:10 UTC by gqueiroz1

2020-09-11 20:15 UTC, DouglasCalora requested changes

2020-09-11 20:15 UTC, DouglasCalora commented on components/NaveEmbedRatio.vue
> +    console.log(this.$slots.default[0].data.attrs)
remover console

2020-09-11 20:15 UTC, DouglasCalora commented on components/NaveHome.vue
> +.nave__home-container {
nunca começamos sem o "pai", no caso essa deveria ser o `.nave-home`

2020-09-11 20:54 UTC, DouglasCalora approved these changes

2020-09-14 01:40 UTC, caiotarifa requested changes

2020-09-14 01:40 UTC, caiotarifa commented on assets/img/Bild_Vitta.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="313.671" height="83.069" viewBox="0 0 313.671 83.069">
Otimize o SVG no SVGO.

2020-09-14 01:40 UTC, caiotarifa commented on components/NaveEmbedRatio.vue
> +    this.$slots.default[0].data.attrs.class = 'nave-flex-embed__content'
E se eu sem querer chamar o `slot` com um elemento de texto ao invés de bloco? Não seria melhor ter uma `div` no template com essa classe?

2020-09-14 01:40 UTC, caiotarifa commented on components/NaveEmbedRatio.vue
> +.nave-flex-embed {
Parabéns pela iniciativa em criar o próprio plugin, esse tipo de solução própria é bem interessante.

Quando usamos Tailwind dispomos de uma série de plugins de terceiros integrados à solução para economizar o nosso tempo. Para este caso existe o https://github.com/drdogbot7/tailwindcss-responsive-embed.

FYI, não precisa alterar.

2020-09-14 01:40 UTC, caiotarifa commented on components/NaveEmbedRatio.vue
> +  <div class="col-span-6 nave-flex-embed nave__about-video-wrapper">
O que esse `col-span-6` faz aqui? E se eu quiser usar o `EmbedRatio` em um lugar com outro tamanho?

2020-09-14 14:55 UTC, merged